### ISSUE TITLE
determine the number of the checked docker tags(based on the date of creation)

### ISSUE THREAD

**Issue by Shaheen47** [dice-group/Basilisk#4]
do we need to get all the tags ? or it is fine to get for example the latest 10, because we are doing regular checking?

**Comment by bigerl** [comment]
Question here is what would be a good default behavior. 
Based on how typical CI tools work I would suggest: 
- when adding a new hook no tags scheduled for benchmarking
- when a new tag is added afterwards it is scheduled for benchmarking
- tags from before the hook was added should only be benchmarked when explicitly initiated by the user/admin

To make sure we do not miss any tags, I rather retrieve all tags and not only the latest 10.

**Comment by Shaheen47** [comment]
so we should retrieve all the tags that were created after adding the hook, not all the tags from the beginning right?

**Comment by bigerl** [comment]
That would be enough for now, yes. 

But maybe it would be better to retrieve all of them? My thought on this is the following: 
> The user would need to know which tags are available to know which ones they could trigger manually, right? + I would not expect projects to have tons of tags -> We could probably retrieve all tags each time. 

Do tags come with a timestamp when they were created or do you the timestamp separately?

**Comment by Shaheen47** [comment]
Tags have timestamps so it is easy to retrieve them all then select what we want. And a tag can be assigned to another image other than the one it is assigned at a specific moment(for example, the latest tag), so the tag's timestamp will be updated. and an image can be assigned to multiple tags(for example, latest and 2.0.0).
So what I am thinking of is to trigger a benchmark based on new images which will guarantee that an image is benchmarked automatically only once. And when we have a new tag for an already benchmarked image, we just add that tag to the image's tags list.
